#!/usr/bin/env sh

# === Required variables ===
if [ -z "${MRPACK_URL}" ]; then
  echo "❌ ERROR: MRPACK_URL is not set!"
  echo "Please define it via environment variable or docker-compose.yml"
  exit 1
fi

# === Optional variables (with defaults) ===
: "${SERVER_DIR:=/app/mcserver}"
: "${JAVA_ARGS:=-Xmx6G -Xms4G}"

mkdir -p $SERVER_DIR || exit 1

echo "=== mrpack-install: installing or updating modpack ==="
mrpack-install --optional-disable-all "${MRPACK_URL}" \
  --server-dir "${SERVER_DIR}" || exit 1

echo "=== Configuring Minecraft server==="
cd ${SERVER_DIR}

# --- Create default server.properties if it doesn't exist ---
SERVER_PROPERTIES="./server.properties"

if [ ! -f "$SERVER_PROPERTIES" ]; then
  cat > "$SERVER_PROPERTIES" <<EOL
# Minecraft server properties
# Generated by setup script
accepts-transfers=false
allow-flight=false
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
difficulty=hard
enable-command-block=false
enable-jmx-monitoring=false
enable-query=false
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=false
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
hardcore=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla,fabric
level-name=world
level-seed=
level-type=minecraft\:normal
log-ips=true
max-chained-neighbor-updates=1000000
max-players=20
max-tick-time=60000
max-world-size=29999984
motd=A Modrinth Minecraft Server
network-compression-threshold=256
online-mode=true
op-permission-level=4
player-idle-timeout=0
prevent-proxy-connections=false
pvp=true
query.port=25565
rate-limit=0
rcon.password=
rcon.port=25575
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=
server-port=25565
simulation-distance=10
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=0
sync-chunk-writes=false
text-filtering-config=
use-native-transport=true
view-distance=16
white-list=false
EOL
fi

echo ${JAVA_ARGS} > ./user_jvm_args.txt

echo "=== Starting Minecraft server ==="

if [ ! -f eula.txt ]; then
  echo "eula=true" > eula.txt
fi

for file in *.jar; do
  [ -e "$file" ] || exit 1   # no .jar files found
  mv -- "$file" "srv.jar"
  break
done

echo "=== Launching server: ${SERVER_JAR} ==="

exec java -jar srv.jar @user_jvm_args.txt
